spring.application.name=service-centre-api

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

jwt.expiration=${JWT_EXPIRATION:86400000}
# jwt.expiration=86400000

spring.profiles.active=dev