# Cloud DB — environment variables se aayega
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JWT
jwt.secret=${JWT_SECRET}

# No SQL logs in production
spring.jpa.show-sql=false
logging.level.org.springframework.security=WARN